Normalize stream implementation & friends
Apifier/xlsx-stream pull request #10
Opened 2021-04-09 18:20 UTC by jirimoravcik

Hello,

I propose a solution to #9 and I also propose some new tests #7

### List of changes

- Create new class XLSXTransformStream based on the node.js Transform class with standard interface
- Refactor some magic constants in the code
- Add tests for the Row and XLSXRowTransform components
- Update README.md with new implementation usage
- Update packages with critical vulnerabilities reported by npm

### Things to discuss

- This PR creates a breaking change, should we somehow make this clear with a new major package version?
- The name of the package; While the new component is named XLSXTransformStream, the package name is still xlsx-write-stream.
- The testing of the main component. It seems to be very difficult to write reasonable tests for a stream that outputs data in binary form - Well, an XLSX file is essentially a zip file and writing unit tests for such data does not make sense to me.

If you have any questions or ideas how to improve this PR, feel free to comment here.

2021-04-21 08:00 UTC, mtrunkat requested changes
Some minor comments + we should release this as a major release - `0.1.0`. 

Or we could make it `1.0.0` otherwise we will never release it :). What do you think @gippy?

And as we are making a breaking major release I think that we should add a changelog as this one - https://github.com/apify/apify-client-js/blob/master/CHANGELOG.md

2021-04-21 08:00 UTC, mtrunkat commented on src/templates/cell.js
> +const offset = 25569;
Please add unit and constants should be snake cased: 

```
const OFFSET_DAYS = ...
```

![image](https://user-images.githubusercontent.com/594801/115408113-e5873b00-a1f0-11eb-9662-39163f19a344.png)

2021-04-21 08:00 UTC, mtrunkat commented on src/utils.js
> +        position = remaining % baseString.length;
Nice.

2021-04-21 08:00 UTC, mtrunkat commented on test/XLSXRowTransform.spec.js
> +describe('The XLSXRowTransform', () => {
Perhaps it would be good to add a more complicated example with:
- more rows
- more types to make it future proof (null, undefined, Date, Boolean?)

2021-04-29 07:20 UTC, aheissenberger commented
@mtrunkat great work - I was not able to open the xlsx files in excel as all files unzipped (e.g. "_rels/.rels") except for "sheet1.xml" where empty. I was able to fix this problem by upgrading the archive package to "5.3.0"

**package.json**
```json
{
  "name": "node-xls-stream-write",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "xlsx-write-stream": "git+ssh://git@github.com:jirimoravcik/xlsx-stream.git"
  },
  "resolutions": {
    "xlsx-write-stream/archiver": "git+ssh://git@github.com:archiverjs/node-archiver.git"
  }
}
```

**index.js**
```javascript
import fs from 'fs'
import XLSXTransformStream from 'xlsx-write-stream';
import {Readable} from 'stream'

const inputStream = new Readable({objectMode: true})
// Input stream needs to implement Stream.Readable interface
// and each chunk should be an array of values (only string, date and number are supported value types)
inputStream
    .pipe(new XLSXTransformStream()) // This stream transforms the input into a xlsx format
    .pipe(fs.createWriteStream('file.xlsx'));

inputStream.push(['Hallo', 1])
inputStream.push(null)
```

2021-04-29 07:44 UTC, aheissenberger commented on test/XLSXRowTransform.spec.js
> +describe('The XLSXRowTransform', () => {
Null is already handled correctly which is very important for big Javascript sparse arrays and to create small excel files. :-)

2021-04-29 07:56 UTC, aheissenberger commented
@jirimoravcik @mtrunkat are you interested in a test which checks the created xlsx file is OK?

I would create a minimal xlsx File and then read it with a zip library into a memory object representing all files including content. Then I use `to.matchSnapshot()`. This will allow to detect any missing content if an update of the archive library breaks the generation of ZIP file. 
I thought about using an other excel library (e.g. excels) to read the result but this might not show a missing part as these libraries might also not interpret all files included in the ZIP.

2021-04-29 09:31 UTC, mtrunkat commented
@aheissenberger That would be great if you could create a simple test that we could add to the test suite in this PR to make sure we won't merge it until the test is passing

2021-07-15 11:03 UTC, closed without merging