Feature/normalize stream implementation
Apifier/xlsx-stream pull request #14
Opened 2021-07-08 07:44 UTC by jirimoravcik

A redo of #10 based off develop branch, which is ahead of master, also added new tests to address comments - a check for the whole generated xlsx file. tests for correct representation of null and undefined in cell function.

2021-07-12 15:52 UTC, drobnikj commented
@jirimoravcik Changes look good, as you write please bump the version into 0.1.0 because of breaking changes. Would be good to settle up the changelog same as we had in other repos like https://github.com/apify/apify-cli/blob/master/CHANGELOG.md and describe breaking change there.

2021-07-12 15:57 UTC, drobnikj requested changes
Just one comment otherwise looks good

2021-07-13 07:10 UTC, mtrunkat requested changes

2021-07-13 07:10 UTC, mtrunkat commented on package.json
> +    "version": "0.0.24",
I'd release this as new major 1.0.0 as it's breaking. What do you think?

2021-07-13 12:07 UTC, mtrunkat approved these changes

2021-07-13 14:07 UTC, drobnikj approved these changes

2021-07-15 11:01 UTC, merged